import numpy as np
import time
import nidaq as nidaq
                  
            
# Create a DigitalOutput object for each of the odour valves
odourcontroller1 = nidaq.DigitalOutput('Dev1/port0/line0')
odourcontroller2 = nidaq.DigitalOutput('Dev1/port0/line4')
odourcontroller3 = nidaq.DigitalOutput('Dev1/port0/line3')
odourcontroller4 = nidaq.DigitalOutput('Dev1/port0/line7')
odourcontroller5 = nidaq.DigitalOutput('Dev1/port0/line2')
odourcontroller6 = nidaq.DigitalOutput('Dev1/port0/line5')
finalvalve1controller = nidaq.DigitalOutput('Dev1/port1/line0')
odourcontroller7 = nidaq.DigitalOutput('Dev1/port2/line6') #originally 'Dev1/port2/line6'
odourcontroller8 = nidaq.DigitalOutput('Dev1/port2/line5')
odourcontroller9 = nidaq.DigitalOutput('Dev1/port2/line4')
odourcontroller10 = nidaq.DigitalOutput('Dev1/port1/line7')
odourcontroller11 = nidaq.DigitalOutput('Dev1/port1/line6')
odourcontroller12 = nidaq.DigitalOutput('Dev1/port1/line4') #originally 'Dev1/port1/line4'
finalvalve2controller = nidaq.DigitalOutput('Dev1/port1/line3')
fivevalvecontroller = nidaq.DigitalOutput('Dev1/port1/line1')
threevalvecontroller = nidaq.DigitalOutput('Dev1/port1/line2')
threevalve2controller = nidaq.DigitalOutput('Dev1/port2/line3')


#create trigger plan

def run_calibration(modd,valve,prep_time,wait_time,decay_time):
    
    print('starting calibration for modd',modd,'valve',valve)
    print('waiting for',wait_time,'seconds')

    if modd == 1:
        finalvalve1controller.start()
        fivevalvecontroller.start()
        
        if valve == 1:
            odourcontroller1.start()
            print('odour valve 1 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller1.stop()
            threevalvecontroller.start()
            odourcontroller1.start()
            print('delivering mineral oil')
            time.sleep(decay_time)
            threevalvecontroller.stop()
            odourcontroller1.stop()
            print('end calibration')
        elif valve == 2:
            odourcontroller2.start()
            print('odour valve 2 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller2.stop()
            threevalvecontroller.start()
            odourcontroller1.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalvecontroller.stop()
            odourcontroller1.stop()
            print('end calibration')
        elif valve == 3:
            odourcontroller3.start()
            print('odour valve 3 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller3.stop()
            threevalvecontroller.start()
            odourcontroller1.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalvecontroller.stop()
            odourcontroller1.stop()
            print('end calibration')
        elif valve == 4:
            odourcontroller4.start()
            print('odour valve 4 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller4.stop()
            threevalvecontroller.start()
            odourcontroller1.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalvecontroller.stop()
            odourcontroller1.stop()
            print('end calibration')
        elif valve == 5:
            odourcontroller5.start()
            print('odour valve 5 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller5.stop()
            threevalvecontroller.start()
            odourcontroller1.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalvecontroller.stop()
            odourcontroller1.stop()
            print('end calibration')
        elif valve == 6:
            odourcontroller6.start()
            print('odour valve 6 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller6.stop()
            threevalvecontroller.start()
            odourcontroller1.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalvecontroller.stop()
            odourcontroller1.stop()
            print('end calibration')
        else:
            print('there are only 6 odour valves')
    else:
        finalvalve2controller.start()
        
        if valve == 1:
            odourcontroller7.start()
            print('odour valve 7 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller7.stop()
            threevalve2controller.start()
            odourcontroller7.start()
            print('delivering mineral oil')
            time.sleep(decay_time)
            threevalve2controller.stop()
            odourcontroller7.stop()
            print('end calibration')
        elif valve == 2:
            odourcontroller8.start()
            print('odour valve 8 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller8.stop()
            threevalve2controller.start()
            odourcontroller7.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalve2controller.stop()
            odourcontroller7.stop()
            print('end calibration')
        elif valve == 3:
            odourcontroller9.start()
            print('odour valve 9 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller9.stop()
            threevalve2controller.start()
            odourcontroller7.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalve2controller.stop()
            odourcontroller7.stop()
            print('end calibration')
        elif valve == 4:
            odourcontroller10.start()
            print('odour valve 10 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller10.stop()
            threevalve2controller.start()
            odourcontroller7.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalve2controller.stop()
            odourcontroller7.stop()
            print('end calibration')
        elif valve == 5:
            odourcontroller11.start()
            print('odour valve 11 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller11.stop()
            threevalve2controller.start()
            odourcontroller7.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalve2controller.stop()
            odourcontroller7.stop()
            print('end calibration')
        elif valve == 6:
            odourcontroller12.start()
            print('odour valve 12 on for',prep_time,'seconds')
            time.sleep(prep_time)
            odourcontroller12.stop()
            threevalve2controller.start()
            odourcontroller7.start()
            print('delivering odour')
            time.sleep(decay_time)
            threevalve2controller.stop()
            odourcontroller7.stop()
            print('end calibration')
        else:
            print('there are only 6 odour valves')
       
#make sure all valves are off at the end of the calibration     
def clean_up():
    finalvalve1controller.stop()
    finalvalve2controller.stop()
    fivevalvecontroller.stop()
    threevalvecontroller.stop()
    threevalve2controller.stop()
    odourcontroller1.stop()
    odourcontroller2.stop()
    odourcontroller3.stop()
    odourcontroller4.stop()
    odourcontroller5.stop()
    odourcontroller6.stop()
    odourcontroller7.stop()
    odourcontroller8.stop()
    odourcontroller9.stop()
    odourcontroller10.stop()
    odourcontroller11.stop()
    odourcontroller12.stop()
    finalvalve1controller.close()
    finalvalve2controller.close()
    fivevalvecontroller.close()
    threevalvecontroller.close()
    threevalve2controller.close()
    odourcontroller1.close()
    odourcontroller2.close()
    odourcontroller3.close()
    odourcontroller4.close()
    odourcontroller5.close()
    odourcontroller6.close()
    odourcontroller7.close()
    odourcontroller8.close()
    odourcontroller9.close()
    odourcontroller10.close()
    odourcontroller11.close()
    odourcontroller12.close()
    print('cleaned up')

run_calibration(2,1,2,5,20)
clean_up()
            
